flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/LogService__c.object-meta.xml
<CustomObject>
    <description>Custom Apex Logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG{0000000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>This field will populated if there are any exceptions</description>
    <inlineHelpText>Use this field to indicate if there is any error message encountered</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <description>Endpoint HOST</description>
    <inlineHelpText>Endpoint HOST</inlineHelpText>
    <label>HOST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>This field will populated the  Rest API call methods (POST, PUT, DELETE .etc)</description>
    <inlineHelpText>Use this field to indicate the Rest API Call Method(POST, PUT, DELETE .etc)</inlineHelpText>
    <label>HTTP Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message max:255 chars</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Request Payload
Error: Class.Method Params</description>
    <inlineHelpText>Request Payload
Error: Class.Method Params</inlineHelpText>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/RequestHeaders__c.field-meta.xml
<CustomField>
    <fullName>RequestHeaders__c</fullName>
    <description>Request Header from API call.</description>
    <inlineHelpText>Use this field to show the request header</inlineHelpText>
    <label>Request Headers</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/RequestURI__c.field-meta.xml
<CustomField>
    <fullName>RequestURI__c</fullName>
    <description>This field will be populated with request URI while calling the  Rest API call</description>
    <inlineHelpText>Use this field to show the request URL</inlineHelpText>
    <label>Request URI</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Callout: Endpoint Reponse
Error:  Thrown Error</description>
    <inlineHelpText>Callout: Endpoint Reponse
Error:  Thrown Error</inlineHelpText>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeaders__c</fullName>
    <description>Response Header from API call.</description>
    <inlineHelpText>Use this field to show the response header</inlineHelpText>
    <label>Response Headers</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Callout: Endpoint
Error: class/method</description>
    <inlineHelpText>Callout: Endpoint
Error: class/method</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>This field will be populated with status code (Success -200, failure 500 ..etc)  while calling the  Rest API call</description>
    <inlineHelpText>Use this field to indicate the status code  (Success -200, failure 500 ..etc)</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Log</description>
    <inlineHelpText>Type of Log</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/LogServiceEvent__e.object-meta.xml
<CustomObject>
    <description>Used for handling various platform event using a name to identify the event type and a body that contains a serialized data need for the named event.  General Event is published after the Apex transaction commits where General Immediate Event fires immediately after it is enqueued.</description>
    <label>General Immediate Event</label>
    <pluralLabel>General Immediate Events</pluralLabel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Log Event Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/classes/LogService_Test.cls
/**
 * @description       : 
 * @author            : Tom Snyder <tom@3ddd.com>
 * @group             : 
 * @last modified on  : 2021-05-06
 * @last modified by  : Tom Snyder <tom@3ddd.com>
 * Modifications Log 
 * Ver   Date         Author                      Modification
 * 1.0   2020-12-07   Tom Snyder <tom@3ddd.com>   Initial Version
**/
@isTest
private class LogService_Test {


	static testMethod void test_SimpleMessageLog() {

		LogService.addMessage('UT', 'hello');
		LogService.save();


		LIST<LogService__c> ltests = [Select Type__c, Source__c, Message__c from LogService__c];
		system.assert(ltests.size()==1, 'Exactly 1 log record should be created.');
		LogService__c ltest = ltests[0];
		system.assert(ltest.Source__c=='UT', 'Confirm Source__c is mapped properly');
		system.assert(ltest.Message__c=='hello',  'Confirm Message__c is mapped properly');
	}

	static testMethod void test_SimpleExceptionLog() {

		LogService.addException(new LogService.LogException('Oops',new LogService.LogException('Ouch!')));
		LogService.save();

		LIST<LogService__c> ltests = [Select Type__c, Source__c, ErrorMessage__c from LogService__c];
		system.assert(ltests.size()==1, 'Exactly 1 log record should be created.');
		LogService__c ltest = ltests[0];
		system.debug(ltest);
		system.assert(ltest.Type__c=='Exception', 'Confirm Source__c is mapped properly');
		system.assert(ltest.ErrorMessage__c.contains('Oops') && ltest.ErrorMessage__c.contains('Ouch!'),  'Confirm ErrorMessage__c is contains message and cause');
	}



	static testMethod void test_CalloutSuccess() {


		HttpRequest request = new HttpRequest();
		request.setEndpoint('https://unitTestRUs.com/service');
		request.setHeader('content-type', 'application/json');
		request.setMethod('POST');
		request.setBody('{"param1":"foo"}');

		Test.setMock(HttpCalloutMock.class, new Mock());

		Test.startTest();

		//simulate a success callout
		LogService log = new LogService('UT', request);
		log.appendMessage('Unit Test a callout');
		try {
			Http http = new Http();
			HttpResponse resp = http.send(request);
			log.append(resp);
		}
		catch(exception ex) {
			log.append(ex);
		}
		finally {
			LogService.addLog(log);
		}
		LogService.save();

		Test.stopTest();

		LIST<LogService__c> ltests = [Select Type__c, Source__c, Request__c, RequestHeaders__c, RequestUri__c, 
			Response__c, ResponseHeaders__c, StatusCode__c, HttpMethod__c, Host__c, ErrorMessage__c  from LogService__c];
		system.assert(ltests.size()==1, 'Exactly 1 log record should be created.');
		LogService__c ltest = ltests[0];
		system.debug(ltest);
		system.assertEquals('https://unitTestRUs.com/service',ltest.RequestURI__c, 'Confirm Host__c is mapped properly');
		system.assertEquals('unittestrus.com', ltest.Host__c, 'Confirm Host__c is mapped properly');
		system.assertEquals('POST',ltest.HttpMethod__c, 'Confirm HttpMethod__c is mapped properly');
		system.assertEquals('{"param1":"foo"}',ltest.Request__c, 'Confirm Request__c is mapped properly');
		system.assertEquals('{"answer":"bar"}',ltest.Response__c, 'Confirm Response__c is mapped properly');
		system.assertEquals(200,ltest.StatusCode__c, 'Confirm StatusCode__c is mapped properly');
		system.assertEquals(null,ltest.ErrorMessage__c, 'Confirm ErrorMessage__c is null');
		
		//system.assert(ltest.ErrorMessage__c.contains('Oops') && ltest.ErrorMessage__c.contains('Ouch!'),  'Confirm ErrorMessage__c is contains message and cause');



	}

	static testMethod void coverage() {	
		LogService l= new LogService();
		l.logType='Callout'; 
		l.message='MSG';
		l.source='UT';
		l.severity='ERROR';	
		l.host='callout:service_org';
		l.request='HTTP request BODY';
		l.response='HTTP response BODY';
		l.append(new HttpRequest());
		l.append(new LogService.LogException('Error1'));
		l.append(new LogService.LogException('Error2'));
		l.appendMessage('Message1');
		l.appendMessage('Message2');
		LogService.addLog(l);
		LogService l2= new LogService('UT', new System.RestRequest());
		LogService.addLog(l2);
		LogService.save();
    }

    static testMethod void testPlatformEventSave() {

        Test.startTest();
        // Create a test event instance
        string msg = 'this is a response from a callout...'; 
		LogService.addMessage('UT',msg);
		System.assert(LogService.queue.size()>0);
		LogService.ImmediateSave();  
		Test.getEventBus().deliver(); 
		Test.stopTest();

		System.assertEquals(msg, [Select source__c, Message__c from LogService__c][0].Message__c,'Log record should exist.');
        
		
    }

	private class Mock implements HttpCalloutMock {
        public HTTPResponse respond(HTTPRequest req) {

            // You could assert the request content here
            HTTPResponse res = new HTTPResponse();
            res.setBody('{"answer":"bar"}');
			res.setHeader('content-type', 'application/json');
            res.setStatusCode(200);
            return res;
        }
    }
    

    static testMethod void testPlatformEvent_InvalidType() {

		//Log PlatformEvent (used to save a serialized log async) will also create a log if an error occurs.

        Test.startTest();
		LogServiceEvent__e[] evnts = new LogServiceEvent__e[]{};
		evnts.add(new LogServiceEvent__e(Type__c='UT_Type', body__c='{}'));
		EventBus.publish(evnts);
		Test.getEventBus().deliver(); 
		Test.stopTest();

		LIST<LogService__c> ltests = [Select Type__c, Source__c, ErrorMessage__c from LogService__c];
		system.assert(ltests.size()==1, 'Exactly 1 log record should be created.');
		LogService__c ltest = ltests[0];
		system.debug(ltest);
		//system.assert(ltest.Type__c=='Exception', 'Confirm Source__c is mapped properly');
		system.assert(ltest.ErrorMessage__c.contains('INVALID_TYPE'),  'Confirm ErrorMessage__c is contains message');
    }


	static testMethod void testPlatformEvent_BadJson() {

		//Log PlatformEvent (used to save a serialized log async) will also create a log if an error occurs.

        Test.startTest();
		LogServiceEvent__e[] evnts = new LogServiceEvent__e[]{};
		evnts.add(new LogServiceEvent__e(Type__c='AddLog', body__c='{"bad: JSON"}'));
		EventBus.publish(evnts);
		Test.getEventBus().deliver(); 
		Test.stopTest();

		LIST<LogService__c> ltests = [Select Type__c, Source__c, ErrorMessage__c from LogService__c];
		system.assert(ltests.size()==1, 'Exactly 1 log record should be created.');
		LogService__c ltest = ltests[0];
		system.debug(ltest);
		//system.assert(ltest.Type__c=='Exception', 'Confirm Source__c is mapped properly');
		system.assert(ltest.ErrorMessage__c.contains('Malformed JSON'),  'Confirm ErrorMessage__c');
    }


    /*
        static testMethod void testExceptionLog() {
		
		 Test.startTest();
		
		try {
	       decimal divBy0 = 1/0;	
		} catch (Exception ex) {
			LogService.addException(ex);
			LogService.save();
			system.debug('getLineNumber: '+ex.getLineNumber());
			system.debug('getCause: '+ex.getCause());
			system.debug('getMessage: '+ex.getMessage());
			system.debug('getStackTraceString: '+ex.getStackTraceString());
			system.debug('getTypeName: '+ex.getTypeName());
			LogService__c l = [Select type__c, Message__c from LogService__c];
			System.assertEquals('Exception', l.Type__c); 
			System.assertEquals('Divide by 0', l.Message__c);  
		}			

        Test.stopTest();

    }
	*/
}