flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/LogService__c.object-meta.xml
<CustomObject>
    <description>Custom Apex Logs</description>
    <label>Log</label>
    <nameField>
        <displayFormat>LOG{0000000000}</displayFormat>
        <label>Log Id</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/CallDuration__c.field-meta.xml
<CustomField>
    <fullName>CallDuration__c</fullName>
    <description>The time in Mili-Seconds to process the call in the Salesforce platform</description>
    <inlineHelpText>Use this field to indicate how much time it takes to process the call</inlineHelpText>
    <label>Call Duration (ms)</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/ErrorMessage__c.field-meta.xml
<CustomField>
    <fullName>ErrorMessage__c</fullName>
    <description>This field will populated if there are any exceptions</description>
    <inlineHelpText>Use this field to indicate if there is any error message encountered</inlineHelpText>
    <label>Error Message</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <description>Endpoint HOST</description>
    <inlineHelpText>Endpoint HOST</inlineHelpText>
    <label>HOST</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/HttpMethod__c.field-meta.xml
<CustomField>
    <fullName>HttpMethod__c</fullName>
    <description>This field will populated the  Rest API call methods (POST, PUT, DELETE .etc)</description>
    <inlineHelpText>Use this field to indicate the Rest API Call Method(POST, PUT, DELETE .etc)</inlineHelpText>
    <label>HTTP Method</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Message__c.field-meta.xml
<CustomField>
    <fullName>Message__c</fullName>
    <description>Message max:255 chars</description>
    <label>Message</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Request__c.field-meta.xml
<CustomField>
    <fullName>Request__c</fullName>
    <description>Request Payload
Error: Class.Method Params</description>
    <inlineHelpText>Request Payload
Error: Class.Method Params</inlineHelpText>
    <label>Request</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/RequestHeaders__c.field-meta.xml
<CustomField>
    <fullName>RequestHeaders__c</fullName>
    <description>Request Header from API call.</description>
    <inlineHelpText>Use this field to show the request header</inlineHelpText>
    <label>Request Headers</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/RequestURI__c.field-meta.xml
<CustomField>
    <fullName>RequestURI__c</fullName>
    <description>This field will be populated with request URI while calling the  Rest API call</description>
    <inlineHelpText>Use this field to show the request URL</inlineHelpText>
    <label>Request URI</label>
    <length>4000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <description>Callout: Endpoint Reponse
Error:  Thrown Error</description>
    <inlineHelpText>Callout: Endpoint Reponse
Error:  Thrown Error</inlineHelpText>
    <label>Response</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/ResponseHeaders__c.field-meta.xml
<CustomField>
    <fullName>ResponseHeaders__c</fullName>
    <description>Response Header from API call.</description>
    <inlineHelpText>Use this field to show the response header</inlineHelpText>
    <label>Response Headers</label>
    <length>16000</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Severity__c.field-meta.xml
<CustomField>
    <fullName>Severity__c</fullName>
    <label>Severity</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>ERROR</fullName>
            </value>
            <value>
                <fullName>WARN</fullName>
            </value>
            <value>
                <fullName>INFO</fullName>
            </value>
            <value>
                <fullName>DEBUG</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Source__c.field-meta.xml
<CustomField>
    <fullName>Source__c</fullName>
    <description>Callout: Endpoint
Error: class/method</description>
    <inlineHelpText>Callout: Endpoint
Error: class/method</inlineHelpText>
    <label>Source</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/StatusCode__c.field-meta.xml
<CustomField>
    <fullName>StatusCode__c</fullName>
    <description>This field will be populated with status code (Success -200, failure 500 ..etc)  while calling the  Rest API call</description>
    <inlineHelpText>Use this field to indicate the status code  (Success -200, failure 500 ..etc)</inlineHelpText>
    <label>Status Code</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogService__c/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <description>Type of Log</description>
    <inlineHelpText>Type of Log</inlineHelpText>
    <label>Type</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Callout</fullName>
            </value>
            <value>
                <fullName>Error</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/LogServiceEvent__e.object-meta.xml
<CustomObject>
    <description>Used for handling various platform event using a name to identify the event type and a body that contains a serialized data need for the named event.  General Event is published after the Apex transaction commits where General Immediate Event fires immediately after it is enqueued.</description>
    <label>General Immediate Event</label>
    <pluralLabel>General Immediate Events</pluralLabel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/fields/Body__c.field-meta.xml
<CustomField>
    <fullName>Body__c</fullName>
    <label>Body</label>
    <length>131072</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/LogServiceEvent__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Log Event Type</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/classes/LogService.cls
/**
 * @description : Log details to custom SObject (ie API activity, errors in Aync processes, etc...)
 * 
 *   for simple one liners to add log to queue use static LogService.add{ANY}() methods;  
 *   for tracking the lifecycle of a given proccess in a single log record use Log() constructors, then use properties/append as needed then finally addLog() 
 * 		this is useful for callouts, long processes, tracking duration, multiple messages, etc..
 
 * 
 * 	use save to commit the logs in the queue;
 *	use immediateSave if you want to save the queue using an immediate platformEvent 
 		- causes no DML so can be invoked prior / between callouts
		- will save log regardless if current apex process completes succesfully (committed)


 * @author            : Tom Snyder <tom@3ddd.com>
 * @group             : 
 * @last modified on  : 05-18-2021
 * @last modified by  : Jack D. Pond
 * Modifications LogService 
 * Ver   Date         Author                      Modification
 * 1.0   2020-11-06   Tom Snyder <tom@3ddd.com>   Initial Version
 * 
 * 
 * TODO: make logtype, severity as enum
 * 
**/
public with sharing class LogService {
	
	//properties

	private LogService__c record {get;  set;}

	//collection of log records
	@TestVisible private static LIST<LogService__c> queue = new LIST<LogService__c>();

	//quick access getter/setters
	public string logType { get { return record.type__c; } set { record.type__c=value; }}
	public string message { get { return record.Message__c; } set { record.Message__c=value; }}
	public string source { get { return record.source__c; } set { record.source__c=value; }}
	public string severity { get { return record.severity__c; } set { record.severity__c=value; }}
	public string host { get { return record.host__c; } set { record.host__c = (value!=null) ? value.replace('callout:','') : null; }}
	public string request { get { return record.Request__c; } set { record.Request__c=value; }}
	public string response { get { return record.Response__c; } set { record.Response__c=value; }}
	public boolean hasErrors { get { return !String.isBlank(record.ErrorMessage__c); } }

	//constructors
	public LogService(){
		record=new LogService__c();
		startTimer();
	}
	public LogService(string source, string msg) {		
		LogService__c l= new LogService__c(type__c='Message', source__c=source, Message__c=msg);
		record=l;
		startTimer();
	}

	/*
	public Log(string source, object obj) {		
		LogService__c l= new LogService__c(type__c='Message', source__c=source, Message__c=JSON.serialize(obj));
		record=l;
		startTimer();
	}
	*/

	public LogService(string source, HttpRequest req) { this(source,httpRequest2RestRequest(req),'HTTP_Callout'); }
	public LogService(string source, System.RestRequest req) { this(source,req, 'HTTP_Callin'); }
	public LogService(string source, System.RestRequest req, string typ) { 
		this.record = new LogService__c(Type__c = typ, Source__c = source);
		this.append(req);
		startTimer();
	}


	public dateTime timerStart {get; private set;}
    public void startTimer() {
        this.timerStart=dateTime.now();
    }


	//append... is used for updating to open (current) log;  useful when a log record.
	public void append(Exception ex) { append(ex, 'ERROR'); }
	public void append(Exception ex, string severity)  {
        if (ex!=null) {

			/* TODO
			if (ex instanceof System.DmlException) {
				System.DmlException dmlEx = (System.DmlException) ex;
				string msg = String.format('{0} DML DmlExceptions',new string[]{ string.valueOf(dmlEx.getNumDml())});
				for(integer i=0; i<dmlEx.getNumDml(); i++) {
					...
				}
			} */
			if (this.source==null)	
				this.source = String.isBlank(ex.getStackTraceString()) ? 'Exception:'+ string.valueOf(ex).left(244) :  ex.getStackTraceString().substringBefore(':');

			string errMsg = String.format('{0}\nType: {1}\nStack: {2}\nCause:{3}',new string[]{ ex.getMessage(), ex.getTypeName(), ex.getStackTraceString(), ex.getCause()?.getMessage() });
			if (this.record.ErrorMessage__c!=null) {
				//append error
				errMsg='\n\n'+ errMsg;
            	this.record.ErrorMessage__c+=errMsg;
			}
			else {
				this.record.ErrorMessage__c=errMsg;
			}
			this.severity= (severity==null) ? 'ERROR' : severity;
        }
	}


	public void append(HttpRequest req) {
		append(httpRequest2RestRequest(req));
	}
	public void append(System.RestRequest req) {
		if (req!=null) {
			string hostHeader = req.headers.get('Host'); 
			this.record.Host__c = (hostHeader!=null) ? hostHeader : req.requestURI?.replace('callout:','').replace('https://','').replace('http://','').substringBefore('/')?.toLowercase();
            this.record.HttpMethod__c = req.httpMethod;
            this.record.RequestURI__c = req.requestURI;
            this.record.Request__c = req.requestBody?.toString();
            this.record.RequestHeaders__c = String.valueOf(req.headers);
        }
	}
	public void append(HttpResponse resp) {
		append(httpResponse2RestResponse(resp));
	}
	public void append(System.RestResponse resp) {
        if (resp!=null) {
            this.record.StatusCode__c = resp.statusCode;
			this.record.ResponseHeaders__c = String.valueOf(resp.headers);
            this.record.Response__c = resp.responseBody?.toString();
        }
	}

	/*
	public void append(HttpRequest req, HttpResponse resp) {
		append(httpRequest2RestRequest(req), httpResponse2RestResponse(resp));
	}
	public void append(System.RestRequest req, System.RestResponse resp) {
		append(req);
		append(resp);
	}
	*/

	public void appendMessage(string msg) {
		if (this.record.Message__c!=null) {
			msg='\n\n'+ msg;
		}
		this.record.Message__c+=msg;
		this.severity='ERROR';
	}



	//add... create and push log to the queue;
	public static void addMessage(string source, string msg) {  addMessage(source,msg,null); }
	public static void addMessage(string source, string msg, string severity) {
		LogService__c l= new LogService__c(type__c='Message', source__c=source, message__c=msg, severity__c = severity);
		addLog(l);
	}
	
	public static void addException(Exception ex) {	addException(ex, null); }
	public static void addException(Exception ex, string severity) { addException(null, ex, severity); }
	public static void addException(string source, Exception ex, string severity) {
		LogService l = new LogService();
		l.logType = 'Exception';
		l.source = source;
		l.append(ex, severity);
		addLog(l);
	}

	public static void addLog(LogService l) {
		if (l.timerStart!=null) {
            l.record.CallDuration__c = datetime.now().getTime() - l.timerStart.getTime();
            l.timerStart=null;
        }
		addLog(l.record);
	}
	
	public static void addLog(LogService__c l) {
		//truncate as needed
		Database.DMLOptions dmo = new Database.DMLOptions();
		dmo.allowFieldTruncation = true;
		l.setOptions(dmo);
		queue.add(l);
	}
	

	public static void immediateSave() {
		if (queue.size()>0) {
			LogServiceEvent__e[] evnts = new LogServiceEvent__e[]{};
			//string jsonLog = JSON.serialize(queue);
			//evnts.add(new GeneralImmediateEvent__e(Type__c='Add', body__c=jsonLog));
			for (LogService__c l : queue) {
				string jsonLog = JSON.serialize(new LIST<LogService__c>{l});
				evnts.add(new LogServiceEvent__e(Type__c='AddLog', body__c=jsonLog));
			}
			EventBus.publish(evnts);
			queue.clear();
		}
	}
	

	public static void save() {
		if (queue.size()>0) {
			LIST<Database.Saveresult> irs = database.insert(queue, false);
			integer ordinal = 0;
			for (Database.Saveresult ir : irs) {
				if (ir.success) {
					queue.remove(ordinal);
				}
				else {
					ordinal++;
//					system.debug(ir);
				}
			}
		}	
	}


	//Helpers
	
    private static System.RestRequest httpRequest2RestRequest(HttpRequest request) {
        System.RestRequest restRequest = new System.RestRequest();
        if(request!=null) {
            restRequest.requestBody = request.getBodyAsBlob();
            restRequest.httpMethod = request.getMethod();
            restRequest.requestURI = request.getEndpoint();
			//request.getHeader(key)
        }
        return restRequest;
    }

    private static System.RestResponse httpResponse2RestResponse(HttpResponse resp) {
        System.RestResponse restResp = new System.RestResponse();
        if(resp!=null) {
            restResp.statusCode = resp.getStatusCode();
            restResp.responseBody = resp.getBodyAsBlob();
			for (string k : resp.getHeaderKeys()) { try { restResp.headers.put(k, resp.getHeader(k)); }catch(Exception ex){} }
        }
        return restResp;
    }


	public class LogException extends Exception {}
}