flow_screen_components/workGuide/force-app/main/default/objects/AppProcessDefinition__c/AppProcessDefinition__c.object-meta.xml
<CustomObject>
    <label>App Process Definition</label>
    <nameField>
        <displayFormat>APD-{0000}</displayFormat>
        <label>AppProcessDefinition Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>App Process Definitions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessDefinition__c/fields/StageStepMappings__c.field-meta.xml
<CustomField>
    <fullName>StageStepMappings__c</fullName>
    <label>StageStepMappings</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessDefinition__c/fields/StepFlowMappings__c.field-meta.xml
<CustomField>
    <fullName>StepFlowMappings__c</fullName>
    <label>StepFlowMappings</label>
    <length>5000</length>
    <type>LongTextArea</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/AppProcessEvent__e.object-meta.xml
<CustomObject>
    <label>AppProcessEvent</label>
    <pluralLabel>AppProcessEvents</pluralLabel>
</CustomObject>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/fields/appProcessDefinitionId__c.field-meta.xml
<CustomField>
    <fullName>appProcessDefinitionId__c</fullName>
    <label>appProcessDefinitionId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/fields/appProcessInstanceId__c.field-meta.xml
<CustomField>
    <fullName>appProcessInstanceId__c</fullName>
    <label>appProcessInstanceId</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/fields/appProcessStepId__c.field-meta.xml
<CustomField>
    <fullName>appProcessStepId__c</fullName>
    <label>appProcessStepId</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/fields/parameters__c.field-meta.xml
<CustomField>
    <fullName>parameters__c</fullName>
    <label>parameters</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessEvent__e/fields/status__c.field-meta.xml
<CustomField>
    <fullName>status__c</fullName>
    <label>status</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/AppProcessInstance__c.object-meta.xml
<CustomObject>
    <label>App Process Instance</label>
    <nameField>
        <label>AppProcessInstance Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>App Process Instances</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/fields/App_Process_Definition__c.field-meta.xml
<CustomField>
    <fullName>App_Process_Definition__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>App Process Definition</label>
    <referenceTo>AppProcessDefinition__c</referenceTo>
    <relationshipLabel>App Process Instances</relationshipLabel>
    <relationshipName>App_Process_Instances</relationshipName>
    <type>Lookup</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/fields/currentStage__c.field-meta.xml
<CustomField>
    <fullName>currentStage__c</fullName>
    <label>Current Stage</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/fields/currentStep__c.field-meta.xml
<CustomField>
    <fullName>currentStep__c</fullName>
    <label>Current Step</label>
    <length>80</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/fields/RecordId__c.field-meta.xml
<CustomField>
    <fullName>RecordId__c</fullName>
    <label>RecordId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/objects/AppProcessInstance__c/fields/UserId__c.field-meta.xml
<CustomField>
    <fullName>UserId__c</fullName>
    <label>UserId</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

flow_screen_components/workGuide/force-app/main/default/classes/WorkGuideController.cls
public with sharing class WorkGuideController {
    @AuraEnabled(cacheable=true)
    public static AppProcessInstance__c getCurrentStepInstance(Id userId, Id recordId) {
        List<AppProcessInstance__c> instanceIds = [
                SELECT
                        Id,
                        currentStage__c,
                        currentStep__c,
                        App_Process_Definition__c,
                        App_Process_Definition__r.Name,
                        App_Process_Definition__r.StepFlowMappings__c,
                        App_Process_Definition__r.StageStepMappings__c
                FROM AppProcessInstance__c
                WHERE UserId__c = :userId AND RecordId__c = :recordId
        ];
        System.debug('instanceIds:::' + instanceIds);
        if (instanceIds.isEmpty()) {
            return new AppProcessInstance__c();
        } else {
            return instanceIds[0];
        }
    }
    @AuraEnabled
    public static AppProcessEventResult dispatchAppProcessEvent(Id definitionId, Id instanceId, String step, String status, String parameters) {
        AppProcessEvent__e appProcessEvent = new AppProcessEvent__e(
                appProcessDefinitionId__c = definitionId,
                appProcessInstanceId__c = instanceId,
                appProcessStepId__c = step,
                parameters__c = parameters,
                status__c = status
        );

        AppProcessEventResult eventResult = new AppProcessEventResult();
        List<Database.SaveResult> results = EventBus.publish(new List<AppProcessEvent__e>{
                appProcessEvent
        });
        for (Database.SaveResult result : results) {
            if (!result.isSuccess()) {
                eventResult.isSuccess = false;
                for (Database.Error error : result.getErrors()) {
                    eventResult.message += error.getStatusCode() + ' : ' + error.getMessage();
                }
            } else {
                eventResult.isSuccess = true;
            }
        }
        eventResult.resultObject = appProcessEvent;
        return eventResult;
    }

    public class AppProcessEventResult {
        @AuraEnabled
        public Boolean isSuccess;
        @AuraEnabled
        public SObject resultObject;
        @AuraEnabled
        public String message;
    }
}