flow_apps/FlowUtilities/force-app/main/default/objects/Flow_OneView__c/Flow_OneView__c.object-meta.xml
<CustomObject>
    <description>Object to hold the design of the records being built inside of the Flow OneView utility</description>
    <label>Flow OneView</label>
    <nameField>
        <displayFormat>FOV-{0000000}</displayFormat>
        <label>Flow OneView Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Flow OneViews</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Flow_OneView__c/fields/dataType__c.field-meta.xml
<CustomField>
    <fullName>dataType__c</fullName>
    <label>dataType</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/FlowUtilities/force-app/main/default/objects/Flow_OneView__c/fields/Resource_Metadata__c.field-meta.xml
<CustomField>
    <fullName>Resource_Metadata__c</fullName>
    <description>Used for both Resources &amp; Elements</description>
    <label>Resource Metadata</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/FlowUtilities/force-app/main/default/objects/Flow_OneView__c/fields/Resource_name__c.field-meta.xml
<CustomField>
    <fullName>Resource_name__c</fullName>
    <description>Used for both Resources &amp; Elements</description>
    <label>Resource name</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Flow_OneView__c/fields/Resource_Type__c.field-meta.xml
<CustomField>
    <fullName>Resource_Type__c</fullName>
    <description>Used for both Resources &amp; Elements</description>
    <label>Resource Type</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/FlowUtilities/force-app/main/default/objects/Flow_OneView__c/fields/value__c.field-meta.xml
<CustomField>
    <fullName>value__c</fullName>
    <label>value</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/FlowUtilities/force-app/main/default/classes/ers_CheckForIdsTest.cls
@isTest
public with sharing class ers_CheckForIdsTest {
    
    static testMethod void processFlowResourcesTest() {

        Flow_OneView__c dummyRecord = new Flow_OneView__c();
        dummyRecord.Resource_Metadata__c = '<variables><name>vDummy1</name><dataType>String</dataType><isCollection>false</isCollection><isInput>false</isInput><isOutput>false</isOutput><value><stringValue>0698c00000Ec4CDAAZ</stringValue></value></variables>';
        dummyRecord.Resource_Type__c = 'variables';
        dummyRecord.Resource_name__c = 'vDummy';
        dummyRecord.dataType__c = 'String';
        dummyRecord.value__c = '0698c00000Ec4CDAAZ';
        insert dummyRecord;

        List<Flow_OneView__c> fovRecords = new List<Flow_OneView__c>();
        fovRecords.add(dummyRecord);

        ers_CheckForIds.Requests testRequest = new ers_CheckForIds.Requests();
        List<ers_CheckForIds.Requests> testRequestList = new List<ers_CheckForIds.Requests>();

        // Test single variable
        testRequest.sourceRecords = fovRecords;
        testRequestList.add(testRequest);
        List<ers_CheckForIds.Results> testResultList = ers_CheckForIds.checkForIds(testRequestList);
        Assert.areEqual('1', String.valueOf(testResultList[0].hardcodeRecords.size()));
        testRequestList.clear();

    }

}