flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/PersonalWorkflow__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PersonalWorkflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Action_Description__c.field-meta.xml
<CustomField>
    <fullName>Action_Description__c</fullName>
    <label>Action Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Trigger_Description__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Description__c</fullName>
    <label>Trigger Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/PersonalWorkflowAction__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PersonalAction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PersonalWorkflowActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/Parent_Workflow_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Workflow_Id__c</fullName>
    <label>Parent Workflow Id</label>
    <referenceTo>PersonalWorkflow__c</referenceTo>
    <relationshipLabel>PersonalWorkflowActions</relationshipLabel>
    <relationshipName>PersonalWorkflowActions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/PersonalWorkflowActionInputParam__c.field-meta.xml
<CustomField>
    <fullName>PersonalWorkflowActionInputParam__c</fullName>
    <label>PersonalWorkflowActionInputParam</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/PersonalWorkflowTrigger__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow Trigger</label>
    <nameField>
        <label>Personal Workflow Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Workflow Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/Personal_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Personal_Workflow__c</fullName>
    <label>Personal Workflow</label>
    <referenceTo>PersonalWorkflow__c</referenceTo>
    <relationshipLabel>Personal Workflow Triggers</relationshipLabel>
    <relationshipName>Personal_Workflow_Triggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerCriteriaFormula__c.field-meta.xml
<CustomField>
    <fullName>TriggerCriteriaFormula__c</fullName>
    <label>TriggerCriteriaFormula</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerFilterType__c.field-meta.xml
<CustomField>
    <fullName>TriggerFilterType__c</fullName>
    <description>Determines whether or not the trigger has some filter criteria</description>
    <label>TriggerFilterType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Expression</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggeringEvents__c.field-meta.xml
<CustomField>
    <fullName>TriggeringEvents__c</fullName>
    <label>TriggeringEvents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>CreateAndUpdate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerObjectName__c.field-meta.xml
<CustomField>
    <fullName>TriggerObjectName__c</fullName>
    <label>TriggerObjectName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerType__c.field-meta.xml
<CustomField>
    <fullName>TriggerType__c</fullName>
    <label>TriggerTiming</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/classes/GenerateFlowFromPersonalWorkflowTest.cls
@isTest
public with sharing class GenerateFlowFromPersonalWorkflowTest {
    @isTest
    static void invokeTest() {

        PersonalWorkflow__c personalWorkflow = new PersonalWorkflow__c();
        personalWorkflow.Name = 'Test Personal Workflow';

        personalWorkflow.Action_Description__c = 'Action Description';
        personalWorkflow.Activity__c = 'Activity';
        personalWorkflow.Trigger_Description__c = 'Trigger Description';
        personalWorkflow.Unique_Name__c = 'TestPersonalWorkflow';

        insert personalWorkflow;
        PersonalWorkflowAction__c personalWorkflowAction = new PersonalWorkflowAction__c();
        personalWorkflowAction.Label__c = 'Action Label';
        personalWorkflowAction.Parent_Workflow_Id__c = personalWorkflow.Id;
        personalWorkflowAction.PersonalWorkflowActionInputParam__c = '[{"name":"channelId","newValue":"id","newValueDataType":"String"}]';
        insert personalWorkflowAction;

        PersonalWorkflowTrigger__c personalWorkflowTrigger = new PersonalWorkflowTrigger__c();

        personalWorkflowTrigger.TriggerCriteriaFormula__c = '$Account.Id == TEXT("2")';
        personalWorkflowTrigger.Personal_Workflow__c = personalWorkflow.Id;
        personalWorkflowTrigger.TriggerFilterType__c = 'Expression';
        personalWorkflowTrigger.TriggeringEvents__c = 'Creation of a New Record';
        personalWorkflowTrigger.TriggerObjectName__c = 'Account';
        personalWorkflowTrigger.TriggerType__c = '';
        insert personalWorkflowTrigger;


        GenerateFlowFromPersonalWorkflow.Request request = new GenerateFlowFromPersonalWorkflow.Request();
        request.personalWorkflowId = personalWorkflow.Id;
        GenerateFlowFromPersonalWorkflow.Response response = GenerateFlowFromPersonalWorkflow.Invoke(new List<GenerateFlowFromPersonalWorkflow.Request>{request})[0];

        System.assert(String.isNotEmpty(response.flowXML));
        
        
    }
}