flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/PersonalWorkflow__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow</label>
    <nameField>
        <label>Label</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>PersonalWorkflows</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Action_Description__c.field-meta.xml
<CustomField>
    <fullName>Action_Description__c</fullName>
    <label>Action Description</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Trigger_Description__c.field-meta.xml
<CustomField>
    <fullName>Trigger_Description__c</fullName>
    <label>Trigger Description</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflow__c/fields/Unique_Name__c.field-meta.xml
<CustomField>
    <fullName>Unique_Name__c</fullName>
    <label>Unique Name</label>
    <length>40</length>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/PersonalWorkflowAction__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow Action</label>
    <nameField>
        <displayFormat>A-{0000}</displayFormat>
        <label>PersonalAction Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>PersonalWorkflowActions</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/Label__c.field-meta.xml
<CustomField>
    <fullName>Label__c</fullName>
    <label>Label</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/Parent_Workflow_Id__c.field-meta.xml
<CustomField>
    <fullName>Parent_Workflow_Id__c</fullName>
    <label>Parent Workflow Id</label>
    <referenceTo>PersonalWorkflow__c</referenceTo>
    <relationshipLabel>PersonalWorkflowActions</relationshipLabel>
    <relationshipName>PersonalWorkflowActions</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowAction__c/fields/PersonalWorkflowActionInputParam__c.field-meta.xml
<CustomField>
    <fullName>PersonalWorkflowActionInputParam__c</fullName>
    <label>PersonalWorkflowActionInputParam</label>
    <length>200</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/PersonalWorkflowTrigger__c.object-meta.xml
<CustomObject>
    <label>Personal Workflow Trigger</label>
    <nameField>
        <label>Personal Workflow Trigger Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Personal Workflow Triggers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/Personal_Workflow__c.field-meta.xml
<CustomField>
    <fullName>Personal_Workflow__c</fullName>
    <label>Personal Workflow</label>
    <referenceTo>PersonalWorkflow__c</referenceTo>
    <relationshipLabel>Personal Workflow Triggers</relationshipLabel>
    <relationshipName>Personal_Workflow_Triggers</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerCriteriaFormula__c.field-meta.xml
<CustomField>
    <fullName>TriggerCriteriaFormula__c</fullName>
    <label>TriggerCriteriaFormula</label>
    <length>60</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerFilterType__c.field-meta.xml
<CustomField>
    <fullName>TriggerFilterType__c</fullName>
    <description>Determines whether or not the trigger has some filter criteria</description>
    <label>TriggerFilterType</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>None</fullName>
            </value>
            <value>
                <fullName>Expression</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggeringEvents__c.field-meta.xml
<CustomField>
    <fullName>TriggeringEvents__c</fullName>
    <label>TriggeringEvents</label>
    <type>Picklist</type>
    <valueSet>
        <valueSetDefinition>
            <value>
                <fullName>Create</fullName>
            </value>
            <value>
                <fullName>Update</fullName>
            </value>
            <value>
                <fullName>Delete</fullName>
            </value>
            <value>
                <fullName>CreateAndUpdate</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerObjectName__c.field-meta.xml
<CustomField>
    <fullName>TriggerObjectName__c</fullName>
    <label>TriggerObjectName</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/objects/PersonalWorkflowTrigger__c/fields/TriggerType__c.field-meta.xml
<CustomField>
    <fullName>TriggerType__c</fullName>
    <label>TriggerTiming</label>
    <length>40</length>
    <type>Text</type>
</CustomField>

flow_apps/PersonalWorkflow/force-app/main/default/classes/GenerateFlowFromPersonalWorkflow.cls
public with sharing class GenerateFlowFromPersonalWorkflow {

    @InvocableMethod(label='Generate Flow From Personal Workflow Record' description='Generate Flow From Personal Workflow Record')
    public static List<Response> Invoke (List<Request> requestList) {
        List<Response> responseList = new List<Response>();

        //for(Request req : requestList) {
            PersonalWorkflow__c personalWorkflow = [
                SELECT  Id,
                        Name,
                        Action_Description__c,
                        Activity__c,
                        Trigger_Description__c,
                        Unique_Name__c
                FROM    PersonalWorkflow__c
                WHERE   Id = :requestList[0].personalWorkflowId
                LIMIT   1

            ];

            PersonalWorkflowAction__c personalWorkflowAction = [
                SELECT  Id, 
                        Name, 
                        Label__c,
                        Parent_Workflow_Id__c,
                        PersonalWorkflowActionInputParam__c
                FROM    PersonalWorkflowAction__c
                WHERE   Parent_Workflow_Id__c = :requestList[0].personalWorkflowId
                LIMIT   1
            ];

            PersonalWorkflowTrigger__c personalWorkflowTrigger = [
                SELECT  Id, 
                        Name, 
                        Personal_Workflow__c,
                        TriggerCriteriaFormula__c,
                        TriggerFilterType__c,
                        TriggeringEvents__c,
                        TriggerObjectName__c,
                        TriggerType__c
                FROM    PersonalWorkflowTrigger__c
                WHERE   Personal_Workflow__c = :requestList[0].personalWorkflowId
                LIMIT   1
            ];
        
            String conditionsXML = '';
            System.debug(personalWorkflowTrigger.TriggerCriteriaFormula__c);
            if(String.isNotEmpty(personalWorkflowTrigger.TriggerCriteriaFormula__c)) {
                Map<String,Object> triggerCriteriaFormula = usf3.ExpressionBuilder.disassemblyFormulaString(personalWorkflowTrigger.TriggerCriteriaFormula__c, null);
                List<usf3.ExpressionBuilder.ExpressionLineWrapper> expressionLineList = (List<usf3.ExpressionBuilder.ExpressionLineWrapper>)triggerCriteriaFormula.get('expressionLines');
                for(usf3.ExpressionBuilder.ExpressionLineWrapper expressionLine : expressionLineList) {
                    conditionsXML += '<filters>' + 
                        '<field>' + 
                            expressionLine.fieldName.split('\\.')[1] +
                        '</field>'+
                        '<operator>' +
                            + operatorMap.get(expressionLine.operator) +
                        '</operator>'+
                        '<value>'+
                            '<stringValue>' +
                                + expressionLine.parameter +
                            '</stringValue>'+
                            
                        '</value>'+
                    '</filters>';
                }
                conditionsXML += '<filterLogic>' + triggerCriteriaFormula.get('logicType') + '</filterLogic>';
                
            }


            String actionCallsXML = '';
            String targetReference = '';
            if(String.isNotEmpty(personalWorkflowAction.PersonalWorkflowActionInputParam__c)) {
                List<ActionCallInputsWrapper> actionCallInputList = (List<ActionCallInputsWrapper>)JSON.deserialize(personalWorkflowAction.PersonalWorkflowActionInputParam__c, List<ActionCallInputsWrapper>.class);
                String inputsXML = '';
                
                for(ActionCallInputsWrapper input : actionCallInputList) {
                    inputsXML +=  '<inputParameters>'+
                                            '<name>'+ input.name +'</name>'+
                                            '<value>'+
                                                '<stringValue>'+ input.newValue +'</stringValue>' +
                                        ' </value>'+
                                    '</inputParameters>';
                }
                
                actionCallsXML = String.format(actionCallXMLSample, new List<String> {
                    personalWorkflowAction.Label__c.replace(' ', '_'),
                    personalWorkflowAction.Label__c,
                    inputsXML
                });

                targetReference = '<connector><targetReference>' + personalWorkflowAction.Label__c.replace(' ', '_') + '</targetReference></connector>';
            }

            Response resp = new Response();

            System.debug(conditionsXML);
            resp.flowXML = String.format(flowXMLStructure, new List<String>{
                personalWorkflow.Name,
                targetReference,
                conditionsXML,
                personalWorkflowTrigger.TriggerObjectName__c,
                'Create',
                actionCallsXML
            });
            responseList.add(resp);
        //}

        return responseList;
    }

    public class Request {
        @InvocableVariable(label='Personal Workflow Id')
        public String personalWorkflowId;
    }

    public class Response {
        @InvocableVariable(label='Flow XML')
        public String flowXML;
    }

    public class ActionCallInputsWrapper {
        String name;
        String newValue;
        String newValueDataType;
    }

    static Map<String,String> operatorMap = new Map<String, String> {
        'equals' => 'EqualTo',
        'not_equal_to' => 'NotEqualTo',
        'contains' => 'Contains',
        'does_not_contain' => 'EndsWith',
        'includes' => 'Includes',
        'excludes' => 'Excludes',
        'starts_with' => 'StartsWith',
        'end_with' => 'EndsWith',
        'greater_or_equal' => 'GreaterThanOrEqualTo',
        'greater_then' => 'GreaterThan',
        'less_or_equal' => 'LessThanOrEqualTo',
        'less_then' => 'LessThan'


    };

    static string flowXMLStructure = '<?xml version="1.0" encoding="UTF-8"?>'+
    '<Flow xmlns="http://soap.sforce.com/2006/04/metadata">'+
        '<apiVersion>52.0</apiVersion>'+
        '<interviewLabel>{0} \'{!\' $Flow.CurrentDateTime\'}\'</interviewLabel>'+
        '<label>{0}</label>'+
        '<processMetadataValues>'+
            '<name>BuilderType</name>'+
            '<value>'+
                '<stringValue>LightningFlowBuilder</stringValue>'+
           ' </value>'+
        '</processMetadataValues>'+
        '<processMetadataValues>'+
            '<name>CanvasMode</name>'+
            '<value>'+
                '<stringValue>AUTO_LAYOUT_CANVAS</stringValue>'+
            '</value>'+
        '</processMetadataValues>'+
        '<processMetadataValues>'+
            '<name>OriginBuilderType</name>'+
            '<value>'+
                '<stringValue>LightningFlowBuilder</stringValue>'+
            '</value>'+
        '</processMetadataValues>'+
        '<processType>AutoLaunchedFlow</processType>'+
        '<start>'+
            '<locationX>50</locationX>'+
            '<locationY>0</locationY>'+
            '<scheduledPaths>'+
                '<name>Shedule_Path</name>'+
                '<label>Shedule Path</label>'+
                '<offsetNumber>1</offsetNumber>'+
                '<offsetUnit>Hours</offsetUnit>'+
                '<recordField>LastModifiedDate</recordField>'+
                '<timeSource>RecordField</timeSource>'+
                '{1}' +//'<targetReference>{1}</targetReference>'+
            '</scheduledPaths>'+
            //'<connector>'+
            
            //'</connector>'+
            '{2}'+ //filters 
            '<object>{3}</object>'+ //object name
            '<recordTriggerType>{4}</recordTriggerType>'+// triger type(Create)
            '<triggerType>RecordAfterSave</triggerType>'+
        '</start>'+
        '<status>Active</status>'+
        '{5}' +
    '</Flow>';

    static String actionCallXMLSample = '<actionCalls>'+
            '<name>{0}</name>'+
            '<label>{1}</label>'+
            '<locationX>176</locationX>'+
            '<locationY>335</locationY>'+
            '<actionName>PostToSlack</actionName>'+
            '<actionType>apex</actionType>'+
            '<flowTransactionModel>CurrentTransaction</flowTransactionModel>'+
            '{2}' +
            '<storeOutputAutomatically>true</storeOutputAutomatically>'+
        '</actionCalls>';
}