flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/WebhookInboundEvent__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for inbound webhook; Validate the information received from a webhook using secret token to check the payload signature</description>
    <label>Inbound Webhook</label>
    <pluralLabel>Inbound Webhooks</pluralLabel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <defaultValue>&apos;Webhook2Flow.WebHook2FlowHandler&apos;</defaultValue>
    <description>Entity used by Agent to handle the logic.  (i.e.  flow name, platform event name, etc...)</description>
    <inlineHelpText>Entity used by Agent to handle the logic.  (i.e.  flow name, platform event name, etc...)</inlineHelpText>
    <label>Actor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Header_Signature_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Header_Signature_Parameter__c</fullName>
    <description>The parameter in the header that is being used to pass the digest signature of the payload.  Example, for Github, the header parameter is &quot;X-Hub-Signature-256&quot;</description>
    <inlineHelpText>The parameter in the header that is being used to pass the digest signature of the payload.  Example, for Github, the header parameter is &quot;X-Hub-Signature-256&quot;</inlineHelpText>
    <label>Header Signature Parameter</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <description>The host name under which this webhook2flow may be initiated.  This is to ensure the webhook requests only are allowed through designated interfaces on the instance.</description>
    <inlineHelpText>The host name under which this webhook2flow may be initiated.  This is to ensure the webhook requests only are allowed through designated interfaces on the instance.</inlineHelpText>
    <label>Host</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Payload_Concatenation__c.field-meta.xml
<CustomField>
    <fullName>Payload_Concatenation__c</fullName>
    <description>Some webhooks require concatenation of header information to ensure the payload is secure. The format for this is a set of semicolon delimited strings.  If the string is enclosed in quotes, it will be used as a constant.  Otherwise a header parameter.
Example for Slack: &quot;v0:&quot;;X-Slack-Request-Timestamp;&quot;:&quot;</description>
    <inlineHelpText>Some webhooks require concatenation of header information to ensure the payload is secure. The format for this is a set of semicolon delimited strings.  If the string is enclosed in quotes, it will be used as a constant.  Otherwise a header parameter.
Example for Slack: &quot;v0:&quot;;X-Slack-Request-Timestamp;&quot;:&quot;</inlineHelpText>
    <label>Payload Concatenation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Secret__c.field-meta.xml
<CustomField>
    <fullName>Secret__c</fullName>
    <description>This is the secret used to create a digest signature that validates the payload.  You should always use a random string with high entropy( e.g., ruby -rsecurerandom -e &apos;puts SecureRandom.hex(20)&apos;)</description>
    <inlineHelpText>This is the secret used to create a digest signature that validates the payload.  You should always use a random string with high entropy( e.g., ruby -rsecurerandom -e &apos;puts SecureRandom.hex(20)&apos;)</inlineHelpText>
    <label>Secret</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Signature_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Signature_Prefix__c</fullName>
    <description>Some webhook signatures have an embedded prefix as part of the signature parameter (for example, github uses &quot;sha256=&quot;.  Optional - can be empty if not used.</description>
    <inlineHelpText>Some webhook signatures have an embedded prefix as part of the signature parameter (for example, github uses &quot;sha256=&quot;.  Optional - can be empty if not used.</inlineHelpText>
    <label>Signature Prefix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Signing_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Signing_Algorithm__c</fullName>
    <description>The algorithm used to generate the digest signature to verify the HTTP Request payload</description>
    <inlineHelpText>The algorithm used to generate the digest signature to verify the HTTP Request payload</inlineHelpText>
    <label>Signing Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>hmacSHA256</fullName>
            </value>
            <value>
                <fullName>hmacSHA512</fullName>
            </value>
            <value>
                <fullName>hmacSHA1</fullName>
            </value>
            <value>
                <fullName>hmacMD5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>The name used when referencing the site in the API (Only for Site/Unauthenticated Webhook access)</description>
    <inlineHelpText>The name used when referencing the site in the API (Only for Site/Unauthenticated Webhook access)</inlineHelpText>
    <label>Unique Site URL</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/classes/WebHookProcessor.cls
/**
 * @description       : 
 * @author            : Tom Snyder <tom@3ddd.com>
 * @group             : 
 * @last modified on  : 05-11-2021
 * @last modified by  : Jack D. Pond
 * Modifications Log 
 * Ver   Date         Author                      Modification
 * 1.0   2021-04-21   Tom Snyder <tom@3ddd.com>   Initial Version
**/
global with sharing class WebHookProcessor {

    global interface IWebHookInboundHandler {
        boolean verify(WebhookInboundEvent__mdt config, RestRequest req);
        RestResponse execute(WebhookInboundEvent__mdt config, RestRequest req);
    }

    global virtual class WebHookInboundHandler implements IWebHookInboundHandler {
        global virtual boolean verify(WebhookInboundEvent__mdt config, RestRequest req) {
            return verifyDigestSignature(config, req);
        }
        global virtual RestResponse execute(WebhookInboundEvent__mdt config, RestRequest req) {
            integer divby0 = 1/0;
            throw new WebHookListener.WebHookListenerException('HANDLER_NOT_IMPLEMENTED');
        }
    }

    global class WebHook2FlowHandler extends WebHookInboundHandler {    

    }

    global class WebHook2PlatformEvent extends WebHookInboundHandler {    

    }


    global class WebHook2Apex implements IWebHookInboundHandler  {
           
        global boolean verify(WebhookInboundEvent__mdt config, RestRequest req) {
            try {
                IWebHookInboundHandler customImpl = (IWebHookInboundHandler) Type.forName(config.Actor__c).newInstance(); 
                return customImpl.verify(config, req);
            }
            catch(Exception ex) {
                throw new WebHookListener.WebHookListenerException('BAD_CONFIGURATION', ex);
            }
        }

        global System.RestResponse execute(WebhookInboundEvent__mdt config, RestRequest req) {
            try {
                IWebHookInboundHandler customImpl = (IWebHookInboundHandler) Type.forName(config.Actor__c).newInstance(); 
                return customImpl.execute(config, req);
            }
            catch(Exception ex) {
                throw new WebHookListener.WebHookListenerException('BAD_CONFIGURATION', ex);
            }
        }

    }



    /**
	* @description 
	* @author Jack D. Pond
	* @param req 
	* @param eventConfig 
	* @return Boolean 
	**/
//	private static Boolean verifyDigestSignature(WebhookInboundEvent__mdt eventConfig, RestRequest req){
    private static Boolean verifyDigestSignature(WebhookInboundEvent__mdt eventConfig, RestRequest req){
        Boolean validSignature = eventConfig.Host__c == req.headers.get('Host');
        if (validSignature && eventConfig.Site_Name__c != null && eventConfig.Site_Name__c.trim().length() > 0){
            try {
                validSignature = (UserInfo.getUserId() == 
                    [SELECT GuestUserId,Name FROM Site where Name = :eventConfig.Site_Name__c.trim() limit 1].GuestUserId);
            } catch(Exception e) {
                validSignature = Test.isRunningTest()? true : false;
            }
        }
        try {
            if (validSignature && eventConfig.Signing_Algorithm__c != null && eventConfig.Signing_Algorithm__c.trim().length() > 0 && eventConfig.Signing_Algorithm__c != 'None'){
                String preHashHeader = '';
                if (eventConfig.Payload_Concatenation__c != null && eventConfig.Payload_Concatenation__c.length() > 0 ){
                    List<String> parsePres = eventConfig.Payload_Concatenation__c.split(';');
                    for (String eachPre : parsePres){
                        if(eachPre.contains('"')){
                            preHashHeader += eachPre.replaceAll('"','');
                        } else {
                            preHashHeader += req.headers.get(eachPre);
                        }
                    }
                }
                String createdDigest = eventConfig.Signature_Prefix__c + EncodingUtil.convertToHex(
                        crypto.generateMac(
                            eventConfig.Signing_Algorithm__c,
                            Blob.valueOf(preHashHeader + req.requestBody.toString()),
                            Blob.valueOf(eventConfig.Secret__c)
                        )
                );
                validSignature = (createdDigest == req.headers.get(eventConfig.Header_Signature_Parameter__c));
            }
        } catch(Exception e) {
            validSignature = false;
        }
        return validSignature;
    }


}