flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/WebhookInboundEvent__mdt.object-meta.xml
<CustomObject>
    <description>Metadata for inbound webhook; Validate the information received from a webhook using secret token to check the payload signature</description>
    <label>Inbound Webhook</label>
    <pluralLabel>Inbound Webhooks</pluralLabel>
</CustomObject>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Actor__c.field-meta.xml
<CustomField>
    <fullName>Actor__c</fullName>
    <defaultValue>&apos;Webhook2Flow.WebHook2FlowHandler&apos;</defaultValue>
    <description>Entity used by Agent to handle the logic.  (i.e.  flow name, platform event name, etc...)</description>
    <inlineHelpText>Entity used by Agent to handle the logic.  (i.e.  flow name, platform event name, etc...)</inlineHelpText>
    <label>Actor</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Agent__c.field-meta.xml
<CustomField>
    <fullName>Agent__c</fullName>
    <description>Apex class to use for handling the verification and response.  (should we use a seperate Agent for verification?)</description>
    <inlineHelpText>Apex class to use for handling the verification and response.  (should we use an seperate Agent for verification?)</inlineHelpText>
    <label>Agent (ApexClass)</label>
    <length>100</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Description__c.field-meta.xml
<CustomField>
    <fullName>Description__c</fullName>
    <description>Description and relevant information to describe the connections purpose and other inventory information (including security risks)</description>
    <inlineHelpText>Description and relevant information to describe the connections purpose and other inventory information (including security risks)</inlineHelpText>
    <label>Description</label>
    <length>4096</length>
    <type>LongTextArea</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Header_Signature_Parameter__c.field-meta.xml
<CustomField>
    <fullName>Header_Signature_Parameter__c</fullName>
    <description>The parameter in the header that is being used to pass the digest signature of the payload.  Example, for Github, the header parameter is &quot;X-Hub-Signature-256&quot;</description>
    <inlineHelpText>The parameter in the header that is being used to pass the digest signature of the payload.  Example, for Github, the header parameter is &quot;X-Hub-Signature-256&quot;</inlineHelpText>
    <label>Header Signature Parameter</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Host__c.field-meta.xml
<CustomField>
    <fullName>Host__c</fullName>
    <description>The host name under which this webhook2flow may be initiated.  This is to ensure the webhook requests only are allowed through designated interfaces on the instance.</description>
    <inlineHelpText>The host name under which this webhook2flow may be initiated.  This is to ensure the webhook requests only are allowed through designated interfaces on the instance.</inlineHelpText>
    <label>Host</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Payload_Concatenation__c.field-meta.xml
<CustomField>
    <fullName>Payload_Concatenation__c</fullName>
    <description>Some webhooks require concatenation of header information to ensure the payload is secure. The format for this is a set of semicolon delimited strings.  If the string is enclosed in quotes, it will be used as a constant.  Otherwise a header parameter.
Example for Slack: &quot;v0:&quot;;X-Slack-Request-Timestamp;&quot;:&quot;</description>
    <inlineHelpText>Some webhooks require concatenation of header information to ensure the payload is secure. The format for this is a set of semicolon delimited strings.  If the string is enclosed in quotes, it will be used as a constant.  Otherwise a header parameter.
Example for Slack: &quot;v0:&quot;;X-Slack-Request-Timestamp;&quot;:&quot;</inlineHelpText>
    <label>Payload Concatenation</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Save_Logs__c.field-meta.xml
<CustomField>
    <fullName>Save_Logs__c</fullName>
    <defaultValue>false</defaultValue>
    <description>If checked, this will save a log of each request using the webhook2flow log object</description>
    <inlineHelpText>If checked, this will save a log of each request using the webhook2flow log object</inlineHelpText>
    <label>Save Logs</label>
    <type>Checkbox</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Secret__c.field-meta.xml
<CustomField>
    <fullName>Secret__c</fullName>
    <description>This is the secret used to create a digest signature that validates the payload.  You should always use a random string with high entropy( e.g., ruby -rsecurerandom -e &apos;puts SecureRandom.hex(20)&apos;)</description>
    <inlineHelpText>This is the secret used to create a digest signature that validates the payload.  You should always use a random string with high entropy( e.g., ruby -rsecurerandom -e &apos;puts SecureRandom.hex(20)&apos;)</inlineHelpText>
    <label>Secret</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Signature_Prefix__c.field-meta.xml
<CustomField>
    <fullName>Signature_Prefix__c</fullName>
    <description>Some webhook signatures have an embedded prefix as part of the signature parameter (for example, github uses &quot;sha256=&quot;.  Optional - can be empty if not used.</description>
    <inlineHelpText>Some webhook signatures have an embedded prefix as part of the signature parameter (for example, github uses &quot;sha256=&quot;.  Optional - can be empty if not used.</inlineHelpText>
    <label>Signature Prefix</label>
    <length>50</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Signing_Algorithm__c.field-meta.xml
<CustomField>
    <fullName>Signing_Algorithm__c</fullName>
    <description>The algorithm used to generate the digest signature to verify the HTTP Request payload</description>
    <inlineHelpText>The algorithm used to generate the digest signature to verify the HTTP Request payload</inlineHelpText>
    <label>Signing Algorithm</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>hmacSHA256</fullName>
            </value>
            <value>
                <fullName>hmacSHA512</fullName>
            </value>
            <value>
                <fullName>hmacSHA1</fullName>
            </value>
            <value>
                <fullName>hmacMD5</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/objects/WebhookInboundEvent__mdt/fields/Site_Name__c.field-meta.xml
<CustomField>
    <fullName>Site_Name__c</fullName>
    <description>The name used when referencing the site in the API (Only for Site/Unauthenticated Webhook access)</description>
    <inlineHelpText>The name used when referencing the site in the API (Only for Site/Unauthenticated Webhook access)</inlineHelpText>
    <label>Unique Site URL</label>
    <length>120</length>
    <type>Text</type>
</CustomField>

flow_apps/webhook2flow/force-app/main/default/classes/Webhook2Flow_Test.cls
/**
 * @description       : Webhook2Flow_Test - deployment test class for Webhook2Flow_Test
 * @author            : Jack D. Pond
 * @group             : 
 * @last modified on  : 05-15-2021
 * @last modified by  : Jack D. Pond
 * Modifications Log 
 * Ver   Date         Author         Modification
 * 1.0   03-24-2021   Jack D. Pond   Initial Version
**/
@isTest
public class Webhook2Flow_Test{
	//https://[YourOrg].my.salesforce.com/services/apexrest/Webhook2Flow/[your_flow_API_Name]?parameter1=this+param+value&parameter2=that+param2+value...
    static final Integer BAD_RESPONSE_DEFAULT = 400 ; // BAD_REQUEST
    static final Integer GOOD_RESPONSE_DEFAULT = 200 ; // Normal Response
	private Static Final String HEADER_PARM_TIMENAME = 'X_Test_Time_Stamp';
	private Static Final String METADATA_SIGN_PARAM = 'X_Test_Signature';
	private Static Final String HEADER_PARM_TIMEVALUE = string.valueOfGmt(System.now());
	private Static Final String METADATA_HASH_PREFIX = '"v0:";'+HEADER_PARM_TIMENAME+';":"';
	private Static Final String METADATA_HASH_PREFIX_VALUE = 'v0:'+ HEADER_PARM_TIMEVALUE +':';
	private Static Final String METADATA_SIGN_PREFIX = 'wh2f=';
	private Static Final String METADATA_SIGN_ALGORITH = 'hmacSHA256';
	private Static Final String METADATA_SIGN_SECRET = '8vkiK0qdBe7fxjDBuF2A';  // random value - doesn't correspond to anything
	private Static Final String URIPART_TO_CLASS = '/services/apexrest/Webhook2Flow/';
	private Static Final String URIPART_FLOWNAME = 'Webhook2Flow_Deploy_Test';
	private Static Final String URIPART_FLOWNAME_INVALID = 'xyzyxxz';
	private Static Final String URIPART_FLOWNAME_DEMO = 'Webhook2Flow_Deploy_Test';
	private Static Final String URIPART_GOOD_PARAMS = '?testParamNumber=0'+
        											  	'&testParamText=thisString'+
        												'&testParamBoolean=true'+
       													'&testParamDate=2021-01-29'+
       													'&testParamCurrency=12.34'+
       													'&testParamDateTime=2021-01-29T12:26:00.00Z';
	private Static Final String URIPART_BAD_PARAMS = '?testParamNumber=NotInteger'+
        											  	'&testParamText=0'+
        												'&testParamBoolean=NotBoolean'+
       													'&testParamDate=202129'+
       													'&testParamCurrency=12.34'+
       													'&testParamDateTime=202100.00Z';
    private Static Final String BODY_JSON = 
	'{' + 
	'    "Subject": "2021-01-25 Test Confirmation for Webhook2Flow_Test",' + 
	'    "Description": "2021-01-25 From Postman to Webhook2Flow_Test.",' + 
	'    "SuppliedName": "Le Grand Frommage",' + 
	'    "SuppliedPhone": "2025551212",' + 
	'    "Submission_Date_And_Time": "2021-01-29T12:26:00.00Z",' + 
	'    "SuppliedCompany": "Fubar United",' + 
	'    "SuppliedEmail": "john.doe@example.com",' + 
	'    "Origin": "Chat",' + 
	'    "testContact": {' + 
	'        "Title" : "Test Contact 1",' + 
	'        "LastName" : "Doe 1",' + 
	'        "FirstName" : "John",' + 
	'        "HomePhone": "2025551212",' + 
    '		 "LastCURequestDate": "2021-03-26T12:26:00.00Z"' +
	'    },' + 
	'    "testContactList": [' + 
	'        {' + 
        '        "Title" : "Test Contact 2",' + 
        '        "LastName" : "Roe 1",' + 
        '        "FirstName" : "Jane",' + 
        '        "HomePhone": "2025551213",' + 
        '		 "LastCURequestDate": "2021-03-26T12:26:00.00Z"' +
	'        },' + 
	'        {' + 
        '        "Title" : "Test Contact 3",' + 
        '        "LastName" : "Doe 2",' + 
        '        "FirstName" : "Jane",' + 
        '        "HomePhone": "2025551214",' + 
        '		 "LastCURequestDate": "2021-03-26T12:26:00.00Z"' +
	'        }' + 
	'    ],' + 
	'    "testTextList" : [' + 
	'        "Testing 1,2,3",' + 
	'        "Testing 3,4,5",' + 
	'        "Testing 7,8,9"' + 
	'    ],' + 
	'    "testNumberList" : [' + 
	'        1,' + 
	'        2,' + 
	'        3' + 
	'    ],' + 
	'    "testBbooleanList" : [' + 
	'        true,' + 
	'        false,' + 
	'        true' + 
	'    ],' + 
	'    "testDateList" : [' + 
	'        "2021-03-25",' + 
	'        "2021-03-26",' + 
	'        "2021-03-27"' + 
	'    ],' + 
	'    "testDateTimeList" : [' + 
	'        "2021-03-25T12:26:00.00Z",' + 
	'        "2021-03-26T13:27:00.00Z",' + 
	'        "2021-03-27T14:28:00.00Z"' + 
	'    ],' + 
	'    "testCurrencyList" : [' + 
	'        12.34,' + 
	'        56.78,' + 
	'        90.12' + 
	'    ],' + 
	'    "testParamDate": "2021-01-29",' + 
	'    "testParamDatetime": "2021-01-29T12:26:00.00Z",' + 
	'    "testParamBoolean": true,' + 
	'    "testParamNumber": 101,' + 
	'    "testParamCurrency": 12.34,' + 
	'	 "testApexDefined": {'+
	'        "type" : "message",' + 
	'        "channel" : "D024BE91L",' + 
	'        "user" : "U2147483697",' + 
	'        "text": "Hello hello can you hear me?",' + 
	'        "event_ts": "1355517523.000005",' + 
    '		 "channel_type": "im"' +
	'    },' + 
	'	 "testApexDefinedList": [' +
	'		{'+
	'        	"type" : "message",' + 
	'        	"channel" : "D024BE91L",' + 
	'        	"user" : "U2147483697",' + 
	'        	"text": "Hello hello can you hear me 01?",' + 
	'        	"event_ts": "1355517523.000005",' + 
    '		 	"channel_type": "im"' +
	'    	},' + 
	'		{'+
	'        	"type" : "message",' + 
	'        	"channel" : "D024BE91L",' + 
	'        	"user" : "U2147483697",' + 
	'        	"text": "Hello hello can you hear me 02?",' + 
	'        	"event_ts": "1355517523.000005",' + 
    '		 	"channel_type": "im"' +
	'    	}' + 
	'    ]' + 
	'}'	;

    private Static Final String BODY_JSON_BAD = 
	'{' + 
	'    "Subject": 1,' + 
	'    "Description": 2,' + 
	'    "SuppliedName": 3,' + 
	'    "SuppliedPhone": 4,' + 
	'    "Submission_Date_And_Time__c": "2021-01-29T12:26:00.00Z",' + 
	'    "SuppliedCompany": "Fubar United",' + 
	'    "SuppliedEmail": "john.doe@example.com",' + 
	'    "Origin": "Chat",' + 
	'    "testContact": {' + 
	'        "Title" : "Test Contact 1",' + 
	'        "LastName" : "Doe 1",' + 
	'        "FirstName" : "John",' + 
	'        "HomePhone": "2025551212",' + 
    '		 "LastCURequestDate": "2021-03-26T12:26:00.00Z"' +
	'    },' + 
	'    "testContactList": [' + 
	'        {' + 
        '        "Title" : "Test Contact 2",' + 
        '        "LastName" : "Roe",' + 
        '        "FirstName" : "Jane",' + 
        '        "HomePhone": "2025551213",' + 
        '		 "LastCURequestDate": "BadDateTime"' +
	'        },' + 
	'        {' + 
        '        "Title" : "Test Contact 2",' + 
        '        "LastName" : "Doe 2",' + 
        '        "FirstName" : "Jane",' + 
        '        "HomePhone": "2025551214",' + 
        '		 "LastCURequestDate": "BadDateTime"' +
	'        }' + 
	'    ],' + 
	'    "testTextList" : [' + 
	'        0,' + 
	'        1,' + 
	'        2' + 
	'    ],' + 
	'    "testNumberList" : [' + 
	'        "BadNumber",' + 
	'        "BadNumber",' + 
	'        "BadNumber"' + 
	'    ],' + 
	'    "testBooleanList" : [' + 
	'        "BadBoolean",' + 
	'        "BadBoolean",' + 
	'        "BadBoolean"' + 
	'    ],' + 
	'    "testDateList" : [' + 
	'        "BadDate",' + 
	'        "BadDate",' + 
	'        "BadDate"' + 
	'    ],' + 
	'    "testDatetimeList" : [' + 
	'        "BadDateTime",' + 
	'        "BadDateTime",' + 
	'        "BadDateTime"' + 
	'    ],' + 
	'    "testUnsupportedCurrencyList" : [' + 
	'        12.34,' + 
	'        56.78,' + 
	'        90.12' + 
	'    ],' + 
	'    "testParamText": -1,' + 
	'    "testParamDate": "BadDate",' + 
	'    "testParamDatetime": "BadDateTime",' + 
	'    "testParamBoolean": "BadBoolean",' + 
	'    "testParamNumber": "BadNumber",' + 
	'    "testParamUnsupportedCurrency": "BadCurrency",' + 
	'	 "testApexDefined": {'+
	'        "type" : 1234.56,' + 
	'        "channel" : "D024BE91L",' + 
	'        "user" : "U2147483697",' + 
	'        "text": "Hello hello can you hear me?",' + 
	'        "event_ts": "1355517523.000005",' + 
    '		 "channel_type": "im"' +
	'    },' + 
	'	 "testApexDefinedList": [' +
	'		{'+
	'        	"type" : 123456,' + 
	'        	"channel" : "D024BE91L",' + 
	'        	"user" : "U2147483697",' + 
	'        	"text": "Hello hello can you hear me 01?",' + 
	'        	"event_ts": "1355517523.000005",' + 
    '		 	"channel_type": "im"' +
	'    	},' + 
	'		{'+
	'        	"type" : 123456,' + 
	'        	"channel" : "D024BE91L",' + 
	'        	"user" : "U2147483697",' + 
	'        	"text": "Hello hello can you hear me 02?",' + 
	'        	"event_ts": "1355517523.000005",' + 
    '		 	"channel_type": "im"' +
	'    	}' + 
	'    ]' + 
	'}'	;
    private Static Final String BODY_JSON_SEND_ERRORS = 
	'{' + 
	'    "testWebhookErrors" :  [' + 
	'        {' + 
	'            "message" : "The requested resource does not exist",' + 
	'            "errorCode" : "NOT_FOUND"' + 
	'        },' + 
	'        {' + 
	'            "message" : "This second message to validate multiple errors",' + 
	'            "errorCode" : "BAD_ERROR_MESSAGE_2"' + 
	'        }' + 
	'    ]' + 
	'}'	;

    
	@testSetup static void setup(){
	}

    public static WebhookInboundEvent__mdt getWebhookConfig(String flowName){
        WebhookInboundEvent__mdt testPointDefinitionMDT = null;
        if (flowName == 'Webhook2Flow_Deploy_Test'){
            testPointDefinitionMDT = new WebhookInboundEvent__mdt(
                Agent__c = 'Webhook2Flow.WebHook2FlowHandler',
                Actor__c = URIPART_FLOWNAME,
                DeveloperName = URIPART_FLOWNAME,
                MasterLabel = URIPART_FLOWNAME,
                Description__c = 'test Description',
                Header_Signature_Parameter__c = METADATA_SIGN_PARAM,
                Host__c = URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''),
                Payload_Concatenation__c = METADATA_HASH_PREFIX,
                Save_Logs__c = true,
                Secret__c = METADATA_SIGN_SECRET,				// a randomly generated sequence - not a key to anything
                Signature_Prefix__c = METADATA_SIGN_PREFIX,
                Signing_Algorithm__c = METADATA_SIGN_ALGORITH,
                Site_Name__c = 'noSite'
            );
        }
        return  testPointDefinitionMDT;
    }

	@isTest static void t01_parameters_post_good_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME + URIPART_GOOD_PARAMS;
            request.httpMethod = 'POST';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
//            system.debug('METADATA_HASH_PREFIX_VALUE: '+METADATA_HASH_PREFIX_VALUE);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
//            system.debug(METADATA_SIGN_PARAM+': '+request.headers.get(METADATA_SIGN_PARAM));
            request.addParameter('testParamNumber', '0');
            request.addParameter('testParamText', 'thisString');
            request.addParameter('testParamBoolean', 'true');
            request.addParameter('testParamDate', '2021-01-29');
            request.addParameter('testParamCurrency', '12.34');
            request.addParameter('testParamDatetime', '2021-01-29T12:26:00.00Z');
            request.addParameter('testGenerateContactsParam', 'true');
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPost();
            system.assertEquals(GOOD_RESPONSE_DEFAULT,RestContext.response.statusCode, 't01_parameters_post_good_coverage: Should have been good');
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}

	@isTest static void t02_parameters_bad_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME + URIPART_BAD_PARAMS;
            request.httpMethod = 'POST';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON_BAD);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            request.addParameter('testParamNumber', 'BadNumber');
            request.addParameter('testParamText', '1');
            request.addParameter('testParamBoolean', 'BadBoolean');
            request.addParameter('testParamDate', 'BadDate');
            request.addParameter('testParamUnsupportedCurrency', 'BadCurrency');
            request.addParameter('testParamDatetime', 'BadDateTime');
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPost();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}
	@isTest static void t03_put_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME;
            request.httpMethod = 'PUT';
            request.addHeader('Content-Type', 'application/json');
			request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPut();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}
	@isTest static void t04_delete_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME;
            request.httpMethod = 'DELETE';
            request.addHeader('Content-Type', 'application/json');
			request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doDelete();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}
	@isTest static void t05_get_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME;
            request.httpMethod = 'GET';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doGet();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}
	@isTest static void t06_patch_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME;
            request.httpMethod = 'PATCH';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPatch();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}

	@isTest static void t07_invalidURL_coverage() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME+URIPART_FLOWNAME_INVALID;
            request.httpMethod = 'POST';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPost();
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}
	@isTest static void t09_test_error_generation() {
        if (true){
            RestRequest request = new RestRequest();
            RestResponse resp = new RestResponse();
            request.requestUri = URL.getSalesforceBaseUrl() + URIPART_TO_CLASS + URIPART_FLOWNAME + URIPART_GOOD_PARAMS;
            request.httpMethod = 'POST';
            request.addHeader('Content-Type', 'application/json');
            request.addHeader('Host', URL.getSalesforceBaseUrl().toExternalForm().replaceFirst('https://',''));
            request.addHeader(HEADER_PARM_TIMENAME, HEADER_PARM_TIMEVALUE);
            request.requestBody = Blob.valueOf(BODY_JSON_SEND_ERRORS);
//            system.debug('METADATA_HASH_PREFIX_VALUE: '+METADATA_HASH_PREFIX_VALUE);
            request.addHeader(METADATA_SIGN_PARAM, METADATA_SIGN_PREFIX+EncodingUtil.convertToHex(crypto.generateMac(
                            METADATA_SIGN_ALGORITH,
                            Blob.valueOf(METADATA_HASH_PREFIX_VALUE + request.requestBody.toString()),
                            Blob.valueOf(METADATA_SIGN_SECRET)))
                        );
//            system.debug(METADATA_SIGN_PARAM+': '+request.headers.get(METADATA_SIGN_PARAM));
            request.addParameter('testGenerateContactsParam', 'true'); // Set error in test flow
            RestContext.request = request;
            RestContext.response = resp;
            webhookListener.doPost();
			system.assertEquals(BAD_RESPONSE_DEFAULT,RestContext.response.statusCode,'t09_test_error_generation: Should have returned an error');
            system.debug('RestContext.response.statusCode: '+RestContext.response.statusCode);
            system.debug('RestContext.response: '+RestContext.response.responseBody.toString());
        }
	}

}